./changefileownership.sh ap9@example.edu sfein 1zzF2JnUL4YXLW3UmyqcZGePcfIC7xu6vzJUhz5PKodc
./changefileownership.sh 09asn@example.edu sfein 1Qi-bTgpl38GNgJqY6ZkN0leckga7w6b7
./changefileownership.sh 09asn@example.edu sfein 1Wpju4-cKJkLeBNtdqV_nQ6GKYXeqeYL0
./changefileownership.sh 09asn@example.edu sfein 1ehQHLtg_WqN5hKSYGkKHSa9wi34MoR5c
./changefileownership.sh 09asn@example.edu sfein 1nZ9ihZaL6pxZt39pBCopFKPdqbx5Vl8t
./changefileownership.sh 09asn@example.edu sfein 1xp1OyzhZfN2NusFkTL-oHeu_mAoA5qO-
./changefileownership.sh ap9@example.edu sfein 1-8RKCjTlm1Qg8pJ-OwV2gHoUCtazjVwM
./changefileownership.sh ap9@example.edu sfein 1-bPD4LBQm0dHYK-7qr6dtVBu-I_Ym3Ow
./changefileownership.sh ap9@example.edu sfein 10ft54OKflSWKMSZCNGmZQI_x6POV5iHR
./changefileownership.sh ap9@example.edu sfein 10hciVqNEZUTlJLlOFcM8t0-l9Ojz3Xo0
./changefileownership.sh ap9@example.edu sfein 113qz7mQC9e7uryiFjLVzmTTsGKZA79j6
./changefileownership.sh ap9@example.edu sfein 11aAkds430rFjP1FMP8fMQJjue5Dyx88w
./changefileownership.sh ap9@example.edu sfein 11apPy116QkgdrggCKMKXdFI8L2j5z0Z-
./changefileownership.sh ap9@example.edu sfein 122C4G6lD0lqeahfrb6lrMJu6fPqgIOc5
./changefileownership.sh ap9@example.edu sfein 12Ef_hHBUTskIELinvv0dxJ9r9kryYwv2
./changefileownership.sh ap9@example.edu sfein 12UxNu97-cwFimx0BiHnHPuoeLuubVfDg
./changefileownership.sh ap9@example.edu sfein 12fOSKb4WlG6vKwV04_1nRypfYXp9GVSeSDT_nd5FQTU
./changefileownership.sh ap9@example.edu sfein 13GIKeHejn5SaGDO6qVccTsWCZcVsmDc7
./changefileownership.sh ap9@example.edu sfein 13m40cT-uzAto8Ms15uuM89FqYKrngLBK
./changefileownership.sh ap9@example.edu sfein 13z28RUdeM4nW_qbS26bZarFA13IgzP77
./changefileownership.sh ap9@example.edu sfein 149tiZ4jJ-Izd4h1izq6iI73WhvDYpnKc
./changefileownership.sh ap9@example.edu sfein 14RpQ6G7pSxYFxqkSe1ZttGln7Imw2uZG
./changefileownership.sh ap9@example.edu sfein 14UVxy8ZHh2dzJk81y44Z-P4FwCMlQ4vM
./changefileownership.sh ap9@example.edu sfein 14fpr95TcucMmK8C4YbaUGQYtM5_EKE-T
./changefileownership.sh ap9@example.edu sfein 14jVJzt8jvXRwVtJvDyxBFHOpmDqYDC_5
./changefileownership.sh ap9@example.edu sfein 14k64K_ddqOtVxIVfYV_cYTlgeKzvPxg4
./changefileownership.sh ap9@example.edu sfein 14pGLz_xXBvFoh1JHVxFEGNQiQWbT3qrK
./changefileownership.sh ap9@example.edu sfein 152jo5uvmSlB3wdDoNX_NA0CIWTPw9IkX
./changefileownership.sh ap9@example.edu sfein 16DlkoklswsK7Vsb8gaXZj5-DQGnGCv-F
./changefileownership.sh ap9@example.edu sfein 16MWBH5iZLw3F3WMyU3TFs6K24XQcZxJK
./changefileownership.sh ap9@example.edu sfein 16WmggYDqS13YSO7_ZlKd-OGSg5EP6t1J
./changefileownership.sh ap9@example.edu sfein 16aTGXoksIUPtuj6iwgI94zHvW8EB5VZN
./changefileownership.sh ap9@example.edu sfein 16bb6SR319JRbFUbj8M5-pWMj5y2qNuIl
./changefileownership.sh ap9@example.edu sfein 16yizMKUjN4OUfue4bGhUvWXvTvPryepM
./changefileownership.sh ap9@example.edu sfein 17HtnZVTb4TtBZN1lZQZXtnCnIhHtCR8h
./changefileownership.sh ap9@example.edu sfein 17RnTiy8AUZ8CSt6JPatqnjPLssay_Rz4
./changefileownership.sh ap9@example.edu sfein 17Wv9rhj_Z-9tcoQ_JSTP25VfOG2tg0FL
./changefileownership.sh ap9@example.edu sfein 182XDRExLCZzKqCRdUxadvYD8ojew-ShR
./changefileownership.sh ap9@example.edu sfein 18FHblOwfTk2QGIK1gSjOJUfptoM04XCX
./changefileownership.sh ap9@example.edu sfein 18JqkyGDxmOpTjJkYob2Sd_ySEEBRNsCp
./changefileownership.sh ap9@example.edu sfein 18orTYiuYPcNnsk0varQ9wng0h_fkGOgM
./changefileownership.sh ap9@example.edu sfein 18vGGUCfTO7RKXKfgHTX_DTJ7sszAxeIw
./changefileownership.sh ap9@example.edu sfein 18ySjQE6UHumvtp7oH5V_Duf4zs3Oeebb
./changefileownership.sh ap9@example.edu sfein 19N0-tejv57vvfUwl575dBcNULkNjnFOj
./changefileownership.sh ap9@example.edu sfein 19Waiiycg0ZQFkWee9lmyyjwEdq2xJOwG
./changefileownership.sh ap9@example.edu sfein 1A9CcM1E0q7EkjSkfXzDH3I-h6fn-7hjs
./changefileownership.sh ap9@example.edu sfein 1AFvLrQ5g81hT0aWb7sEVvf5HHZSQeAer
./changefileownership.sh ap9@example.edu sfein 1AGGnUXDEfynBeOtUvPaAjk5t8H_-xqDT
./changefileownership.sh ap9@example.edu sfein 1Ap20sphSvuUpHBmi1uQxnQODiOFZVdwz
./changefileownership.sh ap9@example.edu sfein 1ApB9YRXISJB3qcD5SwXZyAPx7j94wI3v
./changefileownership.sh ap9@example.edu sfein 1BUcd8rtqVoeaxfbvLmckT33Kx3q3QnCm
./changefileownership.sh ap9@example.edu sfein 1Bi48fVVhwCuWP10e7OmmDKIcnTbq8KwK
./changefileownership.sh ap9@example.edu sfein 1BklF4-rlMX4OFxQB4fMx4h3WvUUy2RNB
./changefileownership.sh ap9@example.edu sfein 1BqnJCDFm4I2ai7yJ1lRW11iUBo2Mdvv9
./changefileownership.sh ap9@example.edu sfein 1C23O2GAloSVIpwNtPAmIYi_cVPoahKk7
./changefileownership.sh ap9@example.edu sfein 1C6-80DnNbqXoi6TK_qN3NFp3azozlEV8
./changefileownership.sh ap9@example.edu sfein 1CNK0Jl26oLWCt2mv9LNHmKna8SPmrs0F
./changefileownership.sh ap9@example.edu sfein 1Cg35YGH-a85fAAC2m5HAZxijQmM2l5yJ
./changefileownership.sh ap9@example.edu sfein 1CsAhAQoRldB71vlOUV8oEd4EWQO-8O2Z
./changefileownership.sh ap9@example.edu sfein 1CvslmKKrDbkNG1zkYGK8vXR815eYeDs8
./changefileownership.sh ap9@example.edu sfein 1DLDFAUAKR7mtPcMyzH8xRXDPstto9LOd
./changefileownership.sh ap9@example.edu sfein 1DRbrtTbYqkj644RpFriPVA9wspzE7qL9
./changefileownership.sh ap9@example.edu sfein 1DZG7Z6LwJ5YaWkx0FsoOMoeM5dr95LtT
./changefileownership.sh ap9@example.edu sfein 1DgtDs7fmprgIZbQXRCPWz1aKyYIpRgyt
./changefileownership.sh ap9@example.edu sfein 1DwYzBwX1cIyejxvVnVQ-EcAVvzRw9fuJ
./changefileownership.sh ap9@example.edu sfein 1DxZiWEiKrL1neVzNlgbVrJ85zzFLiArw
./changefileownership.sh ap9@example.edu sfein 1Dx_6ckXlPMk0AplnmNKNIu70D5x6ZCd9
./changefileownership.sh ap9@example.edu sfein 1FVBCUAwDzUR-R7MReADz93QkuTwatnrh
./changefileownership.sh ap9@example.edu sfein 1Gm7SkbRVxXtzDIQwhDlopRF1XuoExFOP
./changefileownership.sh ap9@example.edu sfein 1Gm7Zr1GwVQIa7n3oSokzAyncYY5oM0y5
./changefileownership.sh ap9@example.edu sfein 1GnaYUiwo79gUJCZUP-l2-Db8Di1Ma-rH
./changefileownership.sh ap9@example.edu sfein 1GsheEK2hCm8H18j6k6HMs8MyRH6DBWhk
./changefileownership.sh ap9@example.edu sfein 1GvWrzKBGOd7iUr2CenM-UcxVgluLuRRJ
./changefileownership.sh ap9@example.edu sfein 1H1stpGASsOQtCLwLC5ZrW66O_MnHCMuB
./changefileownership.sh ap9@example.edu sfein 1H3bbTyJMdvAw-_mfLVqMU8Y-DzlV-Z7H
./changefileownership.sh ap9@example.edu sfein 1HO28hbm1y8F9awvDDtsVWCXe7rxbkuXr
./changefileownership.sh ap9@example.edu sfein 1HTOvF2juL3xa_Tb_C9teBwndnVbVcykZ
./changefileownership.sh ap9@example.edu sfein 1HcHjOqetNy5KeuzKS9cFLKg-o2gizcVP
./changefileownership.sh ap9@example.edu sfein 1INfJBndB3wlqffhTVAxmuLQJiembk6hP
./changefileownership.sh ap9@example.edu sfein 1IPUfgFNzJkg22IWILSTANE5kbeMly5lq
./changefileownership.sh ap9@example.edu sfein 1J9B6UO1UJwRPzL1KMVPGikZL65d_gCeV
./changefileownership.sh ap9@example.edu sfein 1JI_gSgSKv6KX97hupEZurJ4srqbuhq78
./changefileownership.sh ap9@example.edu sfein 1JJdPg2cuAS6jliO07cTVeud7bkFsaoz_
./changefileownership.sh ap9@example.edu sfein 1JL2PtEn9_NPCzgnliHf8NDRPsUZLl6Kx
./changefileownership.sh ap9@example.edu sfein 1JcjbFiebJQrY3He05_CvyMRIguaBmsmg
./changefileownership.sh ap9@example.edu sfein 1KP_ykJiFEDD0eJH1ljhc7VfeWhW8sE4u
./changefileownership.sh ap9@example.edu sfein 1KfmvnVddB7eWhxzFgohCWXGC2PlBfgsR
./changefileownership.sh ap9@example.edu sfein 1Kn3gkGK5u_aTWMUO6BMOxdbTHGTxaQ3f
./changefileownership.sh ap9@example.edu sfein 1L0JsfmmpTjfbZbu4_Vp0UvEJd8bmek_C
./changefileownership.sh ap9@example.edu sfein 1L3rcRLAOFRI_ECL5i2dqi7PKSJ0OB36_
./changefileownership.sh ap9@example.edu sfein 1LimfWD5llzxF1ZIsHhJrFKRXbnli47b2
./changefileownership.sh ap9@example.edu sfein 1MD2V-sUSPiZrRZQx27nKeWA23Yv6ZxAt
./changefileownership.sh ap9@example.edu sfein 1N-Sbp1tWMcJdju9hoKWluWFRRGsem40a
./changefileownership.sh ap9@example.edu sfein 1N8l-kBNFdR61L5GhyIJDiU5ttco3UdYn
./changefileownership.sh ap9@example.edu sfein 1Nm74X-HOe10WPJ6ZwyBnmN3py5U1WeIT
./changefileownership.sh ap9@example.edu sfein 1NrUD5GNZLtA8YR3LNxnBnosJpczA4AYL
./changefileownership.sh ap9@example.edu sfein 1OE2wz4WPDRaIUxOLQWu6Ol9iufBglEnT
./changefileownership.sh ap9@example.edu sfein 1OJKE37_JiAfRqB3igm0YpDysIV_-NkUD
./changefileownership.sh ap9@example.edu sfein 1PJzcGHl1LPxP0oRiY2oft_0RWK-NeJFa
./changefileownership.sh ap9@example.edu sfein 1PoDBca1VAA6GYhi8qxfra8ijwd_brGxl
./changefileownership.sh ap9@example.edu sfein 1Pv-nSm5zvc5ZFR4Q2dVRr67rKvjprhQc
./changefileownership.sh ap9@example.edu sfein 1QJMH8oP7nALT55PrI1hX7Ft0HynSXySv
./changefileownership.sh ap9@example.edu sfein 1QKeuEa7hM-S2CKbIADUgRX83NCl_1Xyu
./changefileownership.sh ap9@example.edu sfein 1QYY57KXLyd7FXAFxVzgrl6XFsNYIbBOq
./changefileownership.sh ap9@example.edu sfein 1RqAyZkLxTacM-eHYIrngM7KQxELg5HHB
./changefileownership.sh ap9@example.edu sfein 1S-1Xxv0N396BxQDv7X-qPPegDyuwUMyE
./changefileownership.sh ap9@example.edu sfein 1S3cxDAPvXDLWlvkslHzaQh8e9ZKDWhmH
./changefileownership.sh ap9@example.edu sfein 1SMBS1B-gB9i-f94WpE8VeKYaIahc6M44
./changefileownership.sh ap9@example.edu sfein 1Sdp5ZLHmU0JtouEWTSsx8T6wz96ch7Gw
./changefileownership.sh ap9@example.edu sfein 1SyUtXYRuqJ6QwtoBkxhkFwllf0rnprBk
./changefileownership.sh ap9@example.edu sfein 1T3t2saehs1sWvXOcq6HdPbQTmOvB4P_c
./changefileownership.sh ap9@example.edu sfein 1TQPFOdQIXWRL70Z3x8E5y9IPEXoxHYCJ
./changefileownership.sh ap9@example.edu sfein 1TYItbC1w4t2fEieF2sV996VzKsLeqJBK
./changefileownership.sh ap9@example.edu sfein 1U7_C_daoZ2NN7vqGiyEiP2wTv6MdM3gd
./changefileownership.sh ap9@example.edu sfein 1UIBUutgdx2XrLhT2s9TtkUuiByxAnTM0
./changefileownership.sh ap9@example.edu sfein 1UWVq7_SHFU7zuUavUTMLCyy13Pa-45QA
./changefileownership.sh ap9@example.edu sfein 1UXKpe75tbF2ipSiYOhlPhLCpp-qOV647
./changefileownership.sh ap9@example.edu sfein 1UdHcmP2i3kVNh4G7FiTupjv9WjuV4v_w
./changefileownership.sh ap9@example.edu sfein 1VL0PjdSX-5KIqXV0iWN6OEhlu9OAQr72
./changefileownership.sh ap9@example.edu sfein 1VO1M_gHSF9WYaKkJPqU_w96Nidj73aGp
./changefileownership.sh ap9@example.edu sfein 1VVv13ArLO9qXiL2pkFIbOGphwdN5fLlo
./changefileownership.sh ap9@example.edu sfein 1VcRKKWk_LHNNasBJyHcMOuONaPdDcnUi
./changefileownership.sh ap9@example.edu sfein 1VdxTHzXQ3dqZH_79o-UkeqyUiTOoNm86
./changefileownership.sh ap9@example.edu sfein 1W6OHS4Qvo6EPi5orIpyIk-jSOoCrg18l
./changefileownership.sh ap9@example.edu sfein 1WzYS9C-FPLWxdzb9pZ72Bm31Jx1Zn7vS
./changefileownership.sh ap9@example.edu sfein 1XPKwWNPPnzMlB3Imc8ebQv4LWcB1mRDb
./changefileownership.sh ap9@example.edu sfein 1Xe-IyiRDU24lVzCffHp684dKe4cyD98L
./changefileownership.sh ap9@example.edu sfein 1XkE1u9bGPOjAJ3tia-2YJnpVJaeElhF6
./changefileownership.sh ap9@example.edu sfein 1Y-RrsJ4p7BxrZO036C5IAYI3VQbVubXR
./changefileownership.sh ap9@example.edu sfein 1YCR1SMYK0Lh0AUImgCZzul3_9HGO3YTB
./changefileownership.sh ap9@example.edu sfein 1YIWlWrK3dT0kCcv3DsDBDAWOtS6SHvHS
./changefileownership.sh ap9@example.edu sfein 1YTry13Nbmw4IaJEZrjlRUKRE-U2CeNV7
./changefileownership.sh ap9@example.edu sfein 1YYhbzL9ezwk6iybyyO8ngi4iBfRfrSo2
./changefileownership.sh ap9@example.edu sfein 1Yj0axwSPENo6rUR9M13zt4-A1rUefL8c
./changefileownership.sh ap9@example.edu sfein 1YxH2iCrb_fj9AgwUlUgQwAU3dx5IYx6N
./changefileownership.sh ap9@example.edu sfein 1ZJnRfxOvgp2JY4z46rxW7vSttquluLJX
./changefileownership.sh ap9@example.edu sfein 1_DN3Gna6V2mnfI8zUK82CYk9PRG0OnTV
./changefileownership.sh ap9@example.edu sfein 1_RsVfPFGUJSoOUvL8YDoyZkhJQDxitcf
./changefileownership.sh ap9@example.edu sfein 1_S_umZ7HKc3rjM3WwG540_t31riW8oFG
./changefileownership.sh ap9@example.edu sfein 1aPLSjyhvo0rugSCo5uvGBSImgXAvO7s3
./changefileownership.sh ap9@example.edu sfein 1afaNL0hjFgDFErViUvx63eoDl_AFqzK1
./changefileownership.sh ap9@example.edu sfein 1akZf19FrUPY696v91V5gVn46srjGEKie
./changefileownership.sh ap9@example.edu sfein 1b0SkoeHJjKDZkencKv217pfSE-7GVwmN
./changefileownership.sh ap9@example.edu sfein 1bdVkAqz13BujQKmcP3SWS_EXURka6k_P
./changefileownership.sh ap9@example.edu sfein 1bds3XGMG_JG_sChtqzgw58umUMaeBaUR
./changefileownership.sh ap9@example.edu sfein 1bvpRqUxSnN-Ggf6HK1IDJ_lDR6WBwRMp
./changefileownership.sh ap9@example.edu sfein 1cA2u0XziTHemoE-MSx3kkNKfDRAmFZGa
./changefileownership.sh ap9@example.edu sfein 1cNCx4tnBpPv3q6ho6Juglctfje77dPmZ
./changefileownership.sh ap9@example.edu sfein 1cNlYZj6qg2DIlJ91_zxlxdWnbjVos7F6
./changefileownership.sh ap9@example.edu sfein 1coipElxsEUf8IGSg-qRVqHEhwbeUOfY5
./changefileownership.sh ap9@example.edu sfein 1dHl_X8v6BCAAd6M8wYxY0HtCGUTZ8wRR
./changefileownership.sh ap9@example.edu sfein 1dYkhfwmc0D5QISjGZLgR0GmY1xrvmhKm
./changefileownership.sh ap9@example.edu sfein 1eUsvo4KoRhzyRZQkBQ828_EYYx7S3asB
./changefileownership.sh ap9@example.edu sfein 1fEjBuJYwWg-Zem-si2xKjBlVZ9soGurN
./changefileownership.sh ap9@example.edu sfein 1fZP8hASOJb6ybO6gdKjpb3dMYkqvq-aN
./changefileownership.sh ap9@example.edu sfein 1fkAnGEoa2wATirYzxp7U5A9Q7GAyJb_z
./changefileownership.sh ap9@example.edu sfein 1fm9MLSmupc1MqJuGoeYVWe4JMyiS7FWP
./changefileownership.sh ap9@example.edu sfein 1fwOtzEsxNxB8nTgUYtOr7i9zBxSaj2h3
./changefileownership.sh ap9@example.edu sfein 1g37lE00ovrcP0XAXxLSp256y6-Xw6vXH
./changefileownership.sh ap9@example.edu sfein 1g47sQgXvbQ66Wglw29efVFTsnUobz3Pt
./changefileownership.sh ap9@example.edu sfein 1gicFVSCvGA0XCcG-BxOHvU4BjkmrY_hl
./changefileownership.sh ap9@example.edu sfein 1gtfP9ryAUjo2S6Jkvy6l3VaEv3DUxYbN
./changefileownership.sh ap9@example.edu sfein 1gx_w5PjgPuByZ2jBIu2BjtnHN72ls2pQ
./changefileownership.sh ap9@example.edu sfein 1hBV_sCNcQLH7XyY3F30Qcbh_cQvLrjqN
./changefileownership.sh ap9@example.edu sfein 1hNgYwUcjIDXFQNh4UqB7HCo7IO7nI9Z1
./changefileownership.sh ap9@example.edu sfein 1i0qEBfCorhXFN1WhSjDDSHOAtt52mfgG
./changefileownership.sh ap9@example.edu sfein 1i5_GZRS7ScIywHKvpwpfyEdWhP3oyzF4
./changefileownership.sh ap9@example.edu sfein 1iHf-0kK311g2jijwr4oYVetVb5TOAWPy
./changefileownership.sh ap9@example.edu sfein 1iTXIALE_hbFrTkWxOG8jvQWWuyFG_5Y1
./changefileownership.sh ap9@example.edu sfein 1j-q7G31g_Zr4dn1DaWRDZ4J64X3yyOPX
./changefileownership.sh ap9@example.edu sfein 1j2acx8P6OCHvXkctoBr40gIxUu4Fq5v-
./changefileownership.sh ap9@example.edu sfein 1j7EpTBPDoo_0wnxTfF7CH9X2WvH13QnZ
./changefileownership.sh ap9@example.edu sfein 1jF_mHempXPI7OWKstu4secPSTNjN24-o
./changefileownership.sh ap9@example.edu sfein 1ju5gyNCnRxLMraLN15A_1zQoaIyt0yaj
./changefileownership.sh ap9@example.edu sfein 1jvIVNYTfuFwH3nxONYYBI1SbsePprC_N
./changefileownership.sh ap9@example.edu sfein 1kQ_8Xqnvs9GKDyvm-POOyNky30zMUU5W
./changefileownership.sh ap9@example.edu sfein 1kbKK_OsVo1xho8x-09HZ26Fi8EK5XbNb
./changefileownership.sh ap9@example.edu sfein 1lHA-GEAxtAwz1ZaS6Sy1GB8awfcKWi8H
./changefileownership.sh ap9@example.edu sfein 1lKeow6T9UoflvloH_tB4vGtMAfbL8FEt
./changefileownership.sh ap9@example.edu sfein 1lWVwjjOplmTpCrGAUtteugrp-wPfMfEI
./changefileownership.sh ap9@example.edu sfein 1lhWWiBSl3-0s42oqDInQv-Dsou7wP5y0
./changefileownership.sh ap9@example.edu sfein 1lpQk_TRRO5Mv1gUdSbd4Hg4Xhtug2mtx
./changefileownership.sh ap9@example.edu sfein 1lxcVjFMLvAGBs-vkJhYTpLAYXv1JNMHK
./changefileownership.sh ap9@example.edu sfein 1mNTEE1NWZWUvRjHPUzETRuHp8wSVWP8l
./changefileownership.sh ap9@example.edu sfein 1mZo4mCkAjKckTwgIDUlt5Eb6gkrTme0K
./changefileownership.sh ap9@example.edu sfein 1mmnLJo69uM0LqTjsCdUHx0xwT0Wcfwr_
./changefileownership.sh ap9@example.edu sfein 1n-BR5GbuzIn29FjVO7m2UoXSIix_ogm-
./changefileownership.sh ap9@example.edu sfein 1n-kgg2c3E8b6XuHWuaprUwYsCgk9wuyJ
./changefileownership.sh ap9@example.edu sfein 1n6M4dom2abHXgg9_LVoM6RWaisiwNeSR
./changefileownership.sh ap9@example.edu sfein 1nQKzTSDSCdGmdw-jyldS_2XEsxMUV_q9
./changefileownership.sh ap9@example.edu sfein 1ncxBSU3RvR8s3yCqMV3JlJa0XtJbEr46
./changefileownership.sh ap9@example.edu sfein 1ntCFxFxAaL65gKH4a0wvgzoRiZrpG5vR
./changefileownership.sh ap9@example.edu sfein 1nzy9WKaVA_JhRIzsIn7O-pKZQEJj9Lzu
./changefileownership.sh ap9@example.edu sfein 1o5CdHlf0LzhYXawXi6mt51tvCLK7Cngy
./changefileownership.sh ap9@example.edu sfein 1obIVvjqVJfnM0_yrmuICdCbfmFQLbqnj
./changefileownership.sh ap9@example.edu sfein 1oik8Vm98h9lKYzfn8Hj07TqLfdfTN9it
./changefileownership.sh ap9@example.edu sfein 1on2_4OrS4pkvPRk9JLpoUSow9WbrvEg9
./changefileownership.sh ap9@example.edu sfein 1otenBAegD-sHdFkGsUMQL__cTcugedCh
./changefileownership.sh ap9@example.edu sfein 1ouSwUTaZRpMa9OedfgVCyEZBPEC2ywno
./changefileownership.sh ap9@example.edu sfein 1p7sgQSsoMSdkhjzUZMzcKMeDdRelHyCo
./changefileownership.sh ap9@example.edu sfein 1pHFw7PCQe9QwOvtfDid3OgRAn6u3DfgV
./changefileownership.sh ap9@example.edu sfein 1pL5dUwwWpudTzcgtkopI1MDK6l5gpip9
./changefileownership.sh ap9@example.edu sfein 1p_nGRFb_oJpnXVYofY4agvtSi7Q67a9y
./changefileownership.sh ap9@example.edu sfein 1pd0Z_0hJHmMER2R54_AbYfDahiZrsYAc
./changefileownership.sh ap9@example.edu sfein 1q2yl-W7eseFH2YgJlEVSmRTTANPlMFvN
./changefileownership.sh ap9@example.edu sfein 1q8BJfkMI_C_4bDLtDPK9HzP2n9CuAjqb
./changefileownership.sh ap9@example.edu sfein 1qNpZyZ9yjT9ds0nmzuhdmm1krT3pB8Vg
./changefileownership.sh ap9@example.edu sfein 1qUlbKaiLMtWOsLp9BXBjTHQl7qBWU75M
./changefileownership.sh ap9@example.edu sfein 1qdTpQoseRqtIhaOco6yRgu_A71TBSnVo
./changefileownership.sh ap9@example.edu sfein 1qrcXe2GSr6IGn3dv0TGTUBCHEMEuDAib
./changefileownership.sh ap9@example.edu sfein 1r5QDoUxOdYsDgtOwDjtVktzXDWVvm-Qh
./changefileownership.sh ap9@example.edu sfein 1r7Dl5Xcua0wKjF87gebxOfz7yQ088N4D
./changefileownership.sh ap9@example.edu sfein 1rPj3l8hoQC2vfdpqHidQ05Mk_o46xtSy
./changefileownership.sh ap9@example.edu sfein 1rQA7EqoKj-VidiMpuZVrv4PiZqoGm3TI
./changefileownership.sh ap9@example.edu sfein 1rkRtBv_lSotIVyYPYVXhX-UOOTfLTkxx
./changefileownership.sh ap9@example.edu sfein 1rpyeFr2LZftWxOIqBOwDreaFw-lZYFPj
./changefileownership.sh ap9@example.edu sfein 1s6-zv-eh27FfAmjyRj0jnAwNFWe2vaoX
./changefileownership.sh ap9@example.edu sfein 1sQ_rI1iR1JCKtDtYaxUe370buCS0-Khz
./changefileownership.sh ap9@example.edu sfein 1sRTiTCYxiDgYCa7wNWTV3u1MkN3LY5od
./changefileownership.sh ap9@example.edu sfein 1sUXb0uJ8RJjWaeFrje8x8CmJHjo31sbi
./changefileownership.sh ap9@example.edu sfein 1sZTmN6R0zEESZ6IiN9BabLVLht1WDp2q
./changefileownership.sh ap9@example.edu sfein 1sf_kkgDVqF-EyUXJLyj1StIUaifKhwj2
./changefileownership.sh ap9@example.edu sfein 1sk5CwYBqdxA4c5OvcCoqymUWqEy5-_bP
./changefileownership.sh ap9@example.edu sfein 1szrMd78IvbR26V9HF183bz903zPVAWzF
./changefileownership.sh ap9@example.edu sfein 1t61g7tBmJoLlUddNUMpNpkShlVEewc3C
./changefileownership.sh ap9@example.edu sfein 1tBpnMBVJiNrUYE05FuZvE_BZfwKU5rG1
./changefileownership.sh ap9@example.edu sfein 1tK6vXw97tVxeh1TwfMu77NTYi_26mmBD
./changefileownership.sh ap9@example.edu sfein 1t_bMtDJldxgm7h9OMRDYiqtKoAeL78rF
./changefileownership.sh ap9@example.edu sfein 1uPwcHA_6YGP2YT4cFImF4wjpCfraDvWa
./changefileownership.sh ap9@example.edu sfein 1uRhG45B79Stz2AuZiprNi3sBwKiVGQPc
./changefileownership.sh ap9@example.edu sfein 1ufM-CcdbDHLcfBLr71p4egoBhUOrY73k
./changefileownership.sh ap9@example.edu sfein 1ukJZdLZCkt8FHWW-wxoFseg_EApP2E68
./changefileownership.sh ap9@example.edu sfein 1ul5ywNYeZqBGKxq17T2hNennKKyKEnip
./changefileownership.sh ap9@example.edu sfein 1uysN9m_nrj-lTiHVYCRSx1t-EG2y5-3z
./changefileownership.sh ap9@example.edu sfein 1v3_0wXKezIk1Ky9Z1btJX_YnUXZhf_88
./changefileownership.sh ap9@example.edu sfein 1vB0DE4f5CJ4XsctqC_jvRhFOtEd_SUFe
./changefileownership.sh ap9@example.edu sfein 1wEuvv9pgtw0pRE1OYoKx4ncbmyKnjNBT
./changefileownership.sh ap9@example.edu sfein 1wi6cHtxGgsqoHm_VGUIpfi9L1oaFnNeF
./changefileownership.sh ap9@example.edu sfein 1xJTeR6ihuknYMtx1M060oOYp-xEkcQSm
./changefileownership.sh ap9@example.edu sfein 1xKUVB7bOMgKmkeF48zykxaHHr5JJqetZ
./changefileownership.sh ap9@example.edu sfein 1xLSAIvQ1ACtsSgRWQGrGWx5AHW5L3F_V
./changefileownership.sh ap9@example.edu sfein 1xk3of-Yo16pYyCaMIISdP2bAlwNNu490
./changefileownership.sh ap9@example.edu sfein 1y6kx338G_9DuPBDH_4ysBMSwFdCY1MGf
./changefileownership.sh ap9@example.edu sfein 1yJFWQpHWFamMmCPBMrqnKXt7lFb1wZ6s
./changefileownership.sh ap9@example.edu sfein 1yNLQqj-m-KM3l68thEcHqvPex7m00M6j
./changefileownership.sh ap9@example.edu sfein 1yWT6s0f53iG69YT6noSHsput6eGxAYtY
./changefileownership.sh ap9@example.edu sfein 1z1O5tr8CR854gSRh3kHwN1rQBF1sCZ9D
./changefileownership.sh ap9@example.edu sfein 1zzF2JnUL4YXLW3UmyqcZGePcfIC7xu6vzJUhz5PKodc
